"""
Core engine for the dynamic planning system (Requirement 2.3).

This module implements the central budget and time management logic:
validating actions, advancing time, applying mandatory food/lodging costs,
enforcing the 20% subsidised route cap, and determining work eligibility.
"""

from typing import Dict, List, Optional, Tuple

from ..graph import Graph
from ..models import AircraftConfig, DynamicStep
from .models import DynamicState
from typing import Any


class DynamicPlanError(ValueError):
    """
    Exception raised for dynamic planning validation failures.

    Used throughout the dynamic planning module to signal constraint
    violations such as insufficient budget, insufficient time, invalid
    actions, or subsidised route limit breaches.
    """

    pass


def apply_cost_and_time(
    state: DynamicState,
    rules: Dict[str, float],
    cost_usd: float,
    duration_min: float,
    cost_airport,
    count_stay: bool,
    action_label: str,
    detail: str,
    step_airport_id: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Apply a monetary cost and time duration for an action.

    Validates the action against available budget and time, deducts the
    cost, advances the session clock, logs the action as a DynamicStep,
    and applies any mandatory food/lodging events triggered during the
    action's duration.

    Args:
        state: Current dynamic session state.
        rules: System rules dict (intervals, budget trigger).
        cost_usd: Monetary cost of the action in USD.
        duration_min: Duration of the action in minutes.
        cost_airport: Airport object whose food/lodging costs apply.
        count_stay: Whether the duration counts toward airport stay time.
        action_label: Short label for the step log (e.g. "vuelo", "actividad").
        detail: Human-readable description of the action.
        step_airport_id: Airport to associate with the step (default: current).
        metadata: Additional structured data to attach to the step.

    Raises:
        DynamicPlanError: If budget or time is insufficient.
    """
    validate_action(state, rules, duration_min, cost_usd, cost_airport)

    state.budget_usd -= cost_usd
    state.total_spent += cost_usd
    time_left_after_action, mandatory_events = advance_time(
        state, rules, duration_min, cost_airport, count_stay
    )

    step_airport = step_airport_id or state.current_airport
    state.steps.append(
        DynamicStep(
            airport_id=step_airport,
            action=action_label,
            detail=detail,
            budget_after=state.budget_usd,
            time_left_min=time_left_after_action,
            metadata=metadata or {},
        )
    )

    apply_mandatory_events(state, cost_airport, mandatory_events, time_left_after_action)


def apply_time_only(
    state: DynamicState,
    rules: Dict[str, float],
    duration_min: float,
    cost_airport,
    count_stay: bool,
) -> Tuple[float, List[Dict[str, float]]]:
    """
    Advance time for an action without monetary cost (e.g. working).

    Validates the action against available time, advances the clock,
    triggers mandatory food/lodging events, and does NOT deduct budget.

    Args:
        state: Current dynamic session state.
        rules: System rules dict.
        duration_min: Duration of the action in minutes.
        cost_airport: Airport whose food/lodging costs apply.
        count_stay: Whether time counts toward minimum stay.

    Returns:
        Tuple of (time_left_after, list_of_mandatory_events).

    Raises:
        DynamicPlanError: If time is insufficient.
    """
    validate_action(state, rules, duration_min, 0.0, cost_airport)
    return advance_time(state, rules, duration_min, cost_airport, count_stay)


def apply_mandatory_events(
    state: DynamicState,
    cost_airport,
    mandatory_events: List[Dict[str, float]],
    time_left_after_action: float,
) -> None:
    """
    Apply mandatory food/lodging costs and log them as steps.

    Called after advancing time; deducts each mandatory event's cost
    from the budget and appends a corresponding DynamicStep.

    Args:
        state: Current dynamic session state.
        cost_airport: Airport with food/lodging cost data.
        mandatory_events: List of events generated by advance_time().
        time_left_after_action: Remaining time to record in step logs.
    """
    if not cost_airport:
        return

    for event in mandatory_events:
        event_cost = event["cost"]
        state.budget_usd -= event_cost
        state.total_spent += event_cost
        state.steps.append(
            DynamicStep(
                airport_id=state.current_airport,
                action=event["action"],
                detail=event["detail"],
                budget_after=state.budget_usd,
                time_left_min=time_left_after_action,
                metadata={"cost": event["cost"]},
            )
        )


def validate_action(
    state: DynamicState,
    rules: Dict[str, float],
    duration_min: float,
    cost_usd: float,
    cost_airport,
) -> None:
    """
    Validate that an action can be performed given current resources.

    Checks:
    1. Duration is positive.
    2. Enough time remains.
    3. Enough budget remains (including projected mandatory costs).

    Args:
        state: Current dynamic session state.
        rules: System rules dict.
        duration_min: Duration of the proposed action.
        cost_usd: Direct monetary cost of the action.
        cost_airport: Airport for mandatory cost estimation.

    Raises:
        DynamicPlanError: If any constraint is violated.
    """
    if duration_min <= 0:
        raise DynamicPlanError("Duracion invalida")

    if state.time_left_min - duration_min < 0:
        raise DynamicPlanError("No hay tiempo suficiente para esta accion")

    _, _, mandatory_cost = estimate_mandatory_costs(
        state,
        duration_min,
        rules,
        cost_airport,
    )
    total_cost = cost_usd + mandatory_cost
    if state.budget_usd - total_cost < 0:
        raise DynamicPlanError("Presupuesto insuficiente para esta accion")


def estimate_mandatory_costs(
    state: DynamicState,
    duration_min: float,
    rules: Dict[str, float],
    cost_airport,
) -> Tuple[int, int, float]:
    """
    Estimate mandatory food and lodging costs for a given duration.

    Projects how many meals and lodgings would be triggered if the
    traveller spends the given duration, based on current intervals.

    Args:
        state: Current dynamic session state (for current intervals).
        duration_min: Prospective duration in minutes.
        rules: System rules dict with food_interval_h and lodging_interval_h.
        cost_airport: Airport object with food_cost and lodging_cost.

    Returns:
        Tuple of (meals_count, lodgings_count, total_cost).
    """
    food_interval_min = rules.get("food_interval_h", 8) * 60
    lodging_interval_min = rules.get("lodging_interval_h", 20) * 60

    new_food = state.minutes_since_food + duration_min
    new_lodging = state.minutes_since_lodging + duration_min

    meals = int(new_food // food_interval_min) if food_interval_min > 0 else 0
    lodgings = int(new_lodging // lodging_interval_min) if lodging_interval_min > 0 else 0

    cost = 0.0
    if cost_airport:
        cost += meals * cost_airport.food_cost
        cost += lodgings * cost_airport.lodging_cost

    return meals, lodgings, cost


def advance_time(
    state: DynamicState,
    rules: Dict[str, float],
    duration_min: float,
    cost_airport,
    count_stay: bool,
) -> Tuple[float, List[Dict[str, float]]]:
    """
    Advance the session clock and compute triggered mandatory events.

    Increments the minutes-since-food/lodging counters, counts how many
    intervals have been crossed, generates mandatory event descriptors,
    and decrements the remaining time.

    Args:
        state: Current dynamic session state.
        rules: System rules dict with interval settings.
        duration_min: Minutes to advance.
        cost_airport: Airport whose cost data is used for event generation.
        count_stay: If True, the duration counts toward stay_min.

    Returns:
        Tuple of (new_time_left_min, list_of_mandatory_event_dicts).
    """
    food_interval_min = rules.get("food_interval_h", 8) * 60
    lodging_interval_min = rules.get("lodging_interval_h", 20) * 60

    state.minutes_since_food += duration_min
    state.minutes_since_lodging += duration_min
    if count_stay:
        state.stay_min += duration_min

    meals = int(state.minutes_since_food // food_interval_min) if food_interval_min > 0 else 0
    lodgings = int(state.minutes_since_lodging // lodging_interval_min) if lodging_interval_min > 0 else 0

    if food_interval_min > 0:
        state.minutes_since_food -= meals * food_interval_min
    if lodging_interval_min > 0:
        state.minutes_since_lodging -= lodgings * lodging_interval_min

    mandatory_events: List[Dict[str, float]] = []
    if cost_airport:
        for _ in range(meals):
            mandatory_events.append(
                {
                    "action": "alimentacion",
                    "detail": f"Alimentacion obligatoria ({cost_airport.food_cost:.2f} USD)",
                    "cost": cost_airport.food_cost,
                }
            )

        for _ in range(lodgings):
            mandatory_events.append(
                {
                    "action": "alojamiento",
                    "detail": f"Alojamiento obligatorio ({cost_airport.lodging_cost:.2f} USD)",
                    "cost": cost_airport.lodging_cost,
                }
            )

    state.time_left_min -= duration_min
    return state.time_left_min, mandatory_events


def calculate_segment_cost(route, cfg: AircraftConfig, state: DynamicState):
    """
    Calculate the monetary cost of a flight segment.

    For non-subsidised routes (base_cost != 0): distance * cost_per_km.
    For subsidised routes (base_cost == 0):
      - If no distance has been travelled yet, cost is $0.
      - Otherwise, enforces the 20% cap: the projected free distance
        (existing + this segment) must not exceed 20% of projected total
        distance. Returns None if the cap would be exceeded.

    Args:
        route: Route object for the segment.
        cfg: Aircraft configuration with cost_per_km.
        state: Current session state with distance trackers.

    Returns:
        Cost in USD, 0.0 for subsidised routes, or None if over cap.
    """
    base_cost = route.distance_km * cfg.cost_per_km
    if route.base_cost != 0:
        return base_cost

    # On the first session leg (no distance travelled), allow any subsidised route.
    if state.total_distance_km == 0:
        return 0.0

    projected_total = state.total_distance_km + route.distance_km
    projected_free = state.free_distance_km + route.distance_km
    max_free = projected_total * 0.2

    if projected_free > max_free:
        return None
    return 0.0


def find_route(graph: Graph, origin: str, destination: str):
    """
    Look up a specific route between two airports.

    Args:
        graph: The airline route graph.
        origin: Origin airport IATA code.
        destination: Destination airport IATA code.

    Returns:
        Route object if found, None otherwise.
    """
    for route in graph.get_outgoing_routes(origin):
        if route.destination == destination:
            return route
    return None


def can_work(state: DynamicState, rules: Dict[str, float]) -> bool:
    """
    Determine whether the traveller is eligible to work.

    Work becomes available when the current budget drops below a
    percentage threshold of the initial budget (default: 35%).

    Args:
        state: Current dynamic session state.
        rules: System rules dict with budget_trigger_percent.

    Returns:
        True if the traveller can work, False otherwise.
    """
    threshold = state.initial_budget * (rules.get("budget_trigger_percent", 35) / 100.0)
    return state.budget_usd < threshold


def is_affordable(state: DynamicState, cost_usd: float, duration_min: float) -> bool:
    """
    Quick check if an action is affordable in terms of both budget and time.

    Does NOT include projected mandatory costs; used for UI display flags.

    Args:
        state: Current dynamic session state.
        cost_usd: Monetary cost of the action.
        duration_min: Duration of the action.

    Returns:
        True if budget >= cost and time_left >= duration.
    """
    return state.budget_usd >= cost_usd and state.time_left_min >= duration_min
