"""
Final report generation and export for dynamic planning (Requirement 2.5).

Aggregates all session steps into a structured report with destinations,
flights, activities, jobs, mandatory fees, and financial totals. Supports
export in JSON and CSV formats.
"""

import json
import csv
import io
from typing import Any, Dict, List

from ..graph import Graph
from .models import DynamicState


def export_report_format(report_data: Dict[str, Any], fmt: str) -> str:
    """
    Serialise a report dictionary into the requested format.

    Args:
        report_data: Report dictionary generated by generate_final_report().
        fmt: Output format ("json" or "csv").

    Returns:
        Formatted string representation of the report.

    Raises:
        ValueError: If the format is not supported.
    """
    if fmt.lower() == "json":
        return json.dumps(report_data, indent=2, ensure_ascii=False)
    elif fmt.lower() == "csv":
        output = io.StringIO()
        writer = csv.writer(output)
        
        writer.writerow(["--- TOTALES ---"])
        writer.writerow(["Presupuesto Inicial", "Total Gastado", "Total Ganado", "Saldo Final", "Tiempo Total (min)", "Total Alimentacion USD", "Total Alojamiento USD"])
        t = report_data.get("totals", {})
        writer.writerow([
            t.get("initial_budget"),
            t.get("total_spent"),
            t.get("total_earned"),
            t.get("final_budget"),
            t.get("total_time_spent_min"),
            t.get("total_food_cost", 0.0),
            t.get("total_lodging_cost", 0.0)
        ])
        writer.writerow([])
        
        writer.writerow(["--- DESTINOS ---"])
        writer.writerow(["ID", "Ciudad", "Pais", "Estadia (min)", "Costo Total"])
        for d in report_data.get("destinations", []):
            writer.writerow([d.get("id"), d.get("city"), d.get("country"), d.get("stay_min"), d.get("total_cost")])
        writer.writerow([])
        
        writer.writerow(["--- VUELOS ---"])
        writer.writerow(["Origen", "Destino", "Aeronave", "Distancia (km)", "Duracion (min)", "Costo USD"])
        for f in report_data.get("flights", []):
            writer.writerow([f.get("origin"), f.get("destination"), f.get("aircraft"), f.get("distance_km"), f.get("duration_min"), f.get("cost_usd")])
        writer.writerow([])
        
        writer.writerow(["--- ACTIVIDADES ---"])
        writer.writerow(["Aeropuerto", "Actividad", "Tipo", "Duracion (min)", "Costo USD"])
        for a in report_data.get("activities", []):
            writer.writerow([a.get("airport_id"), a.get("name"), a.get("kind"), a.get("duration_min"), a.get("cost_usd")])
        writer.writerow([])
        
        writer.writerow(["--- TRABAJOS ---"])
        writer.writerow(["Aeropuerto", "Trabajo", "Horas", "Ingreso USD"])
        for j in report_data.get("jobs", []):
            writer.writerow([j.get("airport_id"), j.get("name"), j.get("hours"), j.get("earned_usd")])
        writer.writerow([])

        writer.writerow(["--- DETALLE DE COBROS OBLIGATORIOS ---"])
        writer.writerow(["Aeropuerto ID", "Aeropuerto Nombre", "Concepto", "Valor USD", "Momento Aplicado (min)"])
        for fee in report_data.get("mandatory_fees", []):
            writer.writerow([
                fee.get("airport_id"),
                fee.get("airport_name"),
                fee.get("action"),
                fee.get("cost_usd"),
                fee.get("moment_min")
            ])
            
        return output.getvalue()
    else:
        raise ValueError(f"Formato no soportado: {fmt}")


def generate_final_report(graph: Graph, state: DynamicState) -> Dict[str, Any]:
    """
    Generate a comprehensive trip report from session state.

    Iterates over all DynamicSteps to aggregate:
      - Destinations visited with stay times and costs.
      - Flight segments with origin, destination, aircraft, distance, duration, cost.
      - Optional activities performed.
      - Work assignments with hours and earnings.
      - Mandatory food/lodging fees with timestamps.
      - Financial totals (initial budget, spent, earned, final balance, time).

    Args:
        graph: The airline route graph (used for airport name lookups).
        state: Current dynamic session state with step history.

    Returns:
        Dictionary with keys: destinations, flights, activities, jobs,
        totals, mandatory_fees.
    """
    destinations_map: Dict[str, Dict[str, Any]] = {}
    flights = []
    activities = []
    jobs = []
    mandatory_fees = []
    
    total_food_cost = 0.0
    total_lodging_cost = 0.0

    for ap_id in state.visited:
        if ap_id not in destinations_map:
            airport = graph.get_airport(ap_id)
            destinations_map[ap_id] = {
                "id": ap_id,
                "name": airport.name if airport else ap_id,
                "city": airport.city if airport else "Desconocida",
                "country": airport.country if airport else "Desconocido",
                "stay_min": 0.0,
                "total_cost": 0.0,
            }

    elapsed_time = 0.0
    for step in state.steps:
        cost = step.metadata.get("cost", 0.0)
        if step.airport_id in destinations_map and cost > 0:
            destinations_map[step.airport_id]["total_cost"] += cost
            
        if step.action == "tiempo_libre":
            duration = step.metadata.get("duration", 0.0)
            elapsed_time += duration
            if step.airport_id in destinations_map:
                destinations_map[step.airport_id]["stay_min"] += duration
        elif step.action == "actividad":
            duration = step.metadata.get("duration", 0.0)
            elapsed_time += duration
            if step.airport_id in destinations_map:
                destinations_map[step.airport_id]["stay_min"] += duration
            activities.append({
                "airport_id": step.airport_id,
                "name": step.metadata.get("name", "Desconocida"),
                "kind": step.metadata.get("kind", "Desconocido"),
                "duration_min": duration,
                "cost_usd": cost,
            })
        elif step.action == "trabajo":
            hours = step.metadata.get("hours", 0.0)
            duration = hours * 60
            elapsed_time += duration
            if step.airport_id in destinations_map:
                destinations_map[step.airport_id]["stay_min"] += duration
            jobs.append({
                "airport_id": step.airport_id,
                "name": step.metadata.get("name", "Desconocido"),
                "hours": hours,
                "earned_usd": step.metadata.get("earned", 0.0),
            })
        elif step.action == "vuelo":
            duration = step.metadata.get("duration", 0.0)
            elapsed_time += duration
            flights.append({
                "origin": step.metadata.get("origin"),
                "destination": step.metadata.get("destination"),
                "aircraft": step.metadata.get("aircraft"),
                "distance_km": step.metadata.get("distance_km", 0.0),
                "duration_min": duration,
                "cost_usd": cost,
            })
        elif step.action == "alimentacion":
            total_food_cost += cost
            airport = graph.get_airport(step.airport_id)
            mandatory_fees.append({
                "airport_id": step.airport_id,
                "airport_name": airport.name if airport else step.airport_id,
                "action": "Alimentación",
                "cost_usd": cost,
                "moment_min": elapsed_time,
            })
        elif step.action == "alojamiento":
            total_lodging_cost += cost
            airport = graph.get_airport(step.airport_id)
            mandatory_fees.append({
                "airport_id": step.airport_id,
                "airport_name": airport.name if airport else step.airport_id,
                "action": "Alojamiento",
                "cost_usd": cost,
                "moment_min": elapsed_time,
            })

    if state.current_airport in destinations_map:
        destinations_map[state.current_airport]["stay_min"] += state.stay_min

    destinations = list(destinations_map.values())

    totals = {
        "initial_budget": state.initial_budget,
        "total_spent": state.total_spent,
        "total_earned": state.total_earned,
        "final_budget": state.budget_usd,
        "total_time_spent_min": 0.0,
        "total_food_cost": total_food_cost,
        "total_lodging_cost": total_lodging_cost,
    }

    total_stay_min = sum(d["stay_min"] for d in destinations)
    total_flight_min = sum(f["duration_min"] for f in flights)
    
    totals["total_time_spent_min"] = total_stay_min + total_flight_min

    return {
        "destinations": destinations,
        "flights": flights,
        "activities": activities,
        "jobs": jobs,
        "totals": totals,
        "mandatory_fees": mandatory_fees,
    }
